### PR TITLE
DEV-17334 Exclude username fields heuristic

### PR DESCRIPTION
**Pull request by abhijeetnarvekar**
Hi,
I have proposed to change excluding search fields list to a generic list of fields to exclude.

### CODE REVIEW

**Comment by acromarco** [comment]
@abhijeetnarvekar The  new code considers a field only as private if (additional to a fixed name) the autocomplete attribute is also set to "off" or "false". Is this a conscious decision or just there because  the existing code detected a search field using this heuristic?
I wonder whether we should exclude ALL fields matching the filter names in case of potential username/tokens fields in order to exclude rather more then less in this case.
With the same reasoning we could exclude other elements like textareas matching the filter names (currently only input fields are excluded.)
@acrork What do you think? Rather exclude more than less?

**Comment by abhijeetnarvekar** [comment]
@acromarco I have created a separate function for undesired fields. Could you have a look its well optimised code.

Thanks,
Abhijeet

**Comment by acromarco** [comment]
@abhijeetnarvekar Actually, the proposed function looks totally fine and also performance wise I don't expect any problem, because it's only applied to already found editable elements and the number of editable elements should be low. If there would be 10000s of them, we would probably get performance problems elsewhere. 

However, you asked explicitly for well optimized code, so I felt pressured to play around a bit and the following code seems to be up to 2-3 times faster (depending on browser and situation) and never slower.

```typescript
const UNDESIRED_FIELD_NAMES = ['username', 'login', 'user[login]', 'authenticity_token'];

export function isProbablyUndesiredField(el: Element) {
  return includes(UNDESIRED_FIELD_NAMES, el.getAttribute('name'));
}

function includes<T>(array: T[], x: T | undefined | null) {
  return array.indexOf(x!) > -1;
}
```
2 changes:

-  UNDESIRED_FIELD_NAMES is defined outside of the function, which is much faster in firefox.
-  Also (surprisingly for me) the includes function of lodash is slow (and complicated https://github.com/lodash/lodash/blob/master/.internal/arrayIncludes.js) compared to a homegrown includes function based on indexOf (we could also just use indexOf directly)


If we ignore IE11, we could use the includes method included in Arrays, which is even a bit more faster:
```
const UNDESIRED_FIELD_NAMES = ['username', 'login', 'user[login]', 'authenticity_token'];

export function isProbablyUndesiredField(el: Element) {
  return UNDESIRED_FIELD_NAMES.includes(el.getAttribute('name')!);
}
```

I'm a bit in favor of just ignoring IE11 and consider the whole autobind functionality as not supported in IE11.

Not sure. We can also just leave your version like it is.
Whatever you prefer :-)

**Comment by abhijeetnarvekar** [comment]
@acromarco Thanks for suggesting optimisation. It's always good to have cleaner, nicer faster code. Yes its just better to ignore IE. I've made the changes, will merge it to master and create a release.

**Pull request merged**
