### PR TITLE
Fixed tsconfig, Added support for Xeditor 6

### PR DESCRIPTION
**Pull request by kpalatzky**
### Fixed TSConfig
- Added libs "es2015.collection", "es2015.proxy", "es2015.core" because they are used in the code
- Changed uppercase to lowercase (Uppercase was not valid)

### Added support for upcoming Xeditor 6 
- Since offset handling changes with Xeditor 6 `insertSpaceAfter` is no longer allowed.

### CODE REVIEW

**Comment by kpalatzky** [comment]
@acromarco It seems that the build errors because of:

```base
ERROR in asset size limit: The following asset(s) exceed the recommended size limit (485 KiB).
This can impact web performance.
Assets: 
  acrolinx-sidebar-sdk.js (493 KiB)
ERROR in entrypoint size limit: The following entrypoint(s) combined asset size exceeds the recommended limit (485 KiB). This can impact web performance.
Entrypoints:
  acrolinx-sidebar-sdk (493 KiB)
      acrolinx-sidebar-sdk.js
```

This should be also a error in the `master`.

**Comment by acromarco** [comment]
@kpalatzky We have this limit to prevent accidental explosion of file size. It's triggered by your PM because you have also updated a lot of dependencies in package-lock.json.
Are these changes in package-lock.json really needed for your PR? If not I would propose to revert this file in the PR, because it makes the merge diff clearer.

**Comment by kpalatzky** [comment]
@acromarco I needed it because i got some errors otherwise.. but i will revert it!

**Comment by kpalatzky** [comment]
I see that the test faild since the test coverage is below the last value. The problem here is that there are no tests in general for Xeditor (this is also relatively hard to do because you need a complete mock interface for the Xeditor).

How do we get on with this @AcrolinxSupport ?

**Comment by acromarco** [comment]
@kpalatzky It's not a big problem to just reduce the required code coverage by some 0.1. It's actually only a  reminder/motivator for ourselves and no strict requirement. The reason for not merging your PR yet is actually a legal question that is internally pending and will be resolved hopefully very soon. Sorry for that.

**Comment by acromarco** [comment]
@kpalatzky Pending things are not pending anymore. Will be merged today. 
Has a new npm release time until Monday?

**Comment by kpalatzky** [comment]
@acromarco Yes it has. Would be nice if the release happens next week.

**Pull request merged**
