### PR TITLE
DEV-12408 removed the condition which check content text is empty or not

### PR DESCRIPTION
**Pull request by gohaterahul**
@acromarco @acrork @pcdeshmukh 
I have removed condition which checks content is empty or not in extractContentForCheck function of multiEditorAdapter.ts file.

### CODE REVIEW

**Comment by acromarco** [comment]
@gohaterahul Your code change does not compile and does not pass the existing tests. I have added in https://github.com/acrolinx/sidebar-sdk-js/blob/master/CONTRIBUTING.md  a description how to compile and run tests locally. 

@acrork  We should improve our build system in order to check pull requests automatically. As far as I know this should work out of the box if we would build on Travis.

**Comment by gohaterahul** [comment]
@acromarco I have removed the unvanted variable and also updated the test cases for multiEditorAdaptor.

**Comment by acromarco** [comment]
@gohaterahul You’ve removed the complete "multi-editor-adapter - maps correctly if first adapter gets empty" test. This test had failed because we’ve replaced the requirement "should send no empty adapter content" with the new requirement "should send empty adapter content too". I think it's still useful to have a test for this new requirement. Therefore I would propose to change the existing test instead of delete it completely.

**Comment by acromarco** [comment]
@gohaterahul  @pcdeshmukh Looks great.

**Pull request merged**
